<?php


namespace app\api\controller;

class AuthBase extends ApiBase
{
    public $userId = 0;
    public $username = '';
    public $authorization = '';
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->authorization = $this->request->header('Authorization');
        if (!$this->authorization || !$this->isLogin()) {
            return $this->show(config('status.not_login'), 'token已过期, 请重新授权');
        }
    }
    
    public function isLogin()
    {
        $userInfo = cache(config('wx.api_token_pre').$this->authorization);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['uid'])) {
            $this->userId = $userInfo['uid'];
            return true;
        }
        return false;
    }
}
